### ISSUE TITLE
Filesystem functions don’t work with Patchwork\Utf8\WindowsStreamWrapper

### ISSUE THREAD

**Issue by Manuela-Fereira** [tchwork/utf8#26]
This wrapper tries to work with files using their short filenames, but PHP can’t handle short names of files which have Unicode long names (see https://bugs.php.net/bug.php?id=65358). Using this wrapper, one can work with folders and delete files (scandir, mkdir, rmdir, unlink), but cannot create, modify, read or upload files (fopen, file_put_contents, file_get_contents, move_uploaded_file).

More exactly, these operations are possible, but only if filenames match current system locale (as well as when we use normal PHP filesystem functions). E.g. if my Windows has russian locale, I can create/upload a file with cyrillic filename but cannot with hebrew or greek, and vice versa - whether WindowsStreamWrapper is included or not.

This makes WindowsStreamWrapper pretty unusable. I also tested old version of this script (WinfsUtf8.php, 2012) with the same result.

Example:
```php
	// Using Windows with english locale (CP1252)

	// 1) Filename string doesn’t match OS locale
	file_put_contents($path . 'εγκυκλοπαίδεια.txt', 'Greek filename');

	// Result with WindowsStreamWrapper:
	// PHP gives warning “failed to open stream”
	// Result without WindowsStreamWrapper:
	// PHP creates a file with messy name (however PHP can see this file as 'εγκυκλοπαίδεια.txt')

	// 2) Filename string matches OS locale
	file_put_contents($path . 'filênàmé.txt', 'Western european filename');

	// With WindowsStreamWrapper:
	// Success
	// Without WindowsStreamWrapper:
	// Success (however filename string must be encoded in CP1252, not UTF-8)
```
Tested on PHP versions 5.5.13 & 5.4.29.

**Comment by nicolas-grekas** [comment]
I was already testing for this buggy behavior so I added the bug reference in commit b349019612228bde6d81edf8910ca505e3c19cbb
https://github.com/kenjiuno/php-wfio is the way to go and WindowsStreamWrapper does work for some use cases as fallback. There is nothing I can do about it unfortunately (or please send a PR if someone has an idea...)
