### ISSUE TITLE
Fix version in installation instructions

### ISSUE THREAD

**Issue by vlakoff** [tchwork/utf8#34]
[Installation instructions](https://github.com/tchwork/utf8#user-content-usage) specify version `~1.2`, but as of today, it needs a "dev" minimum-stability. So I would suggest putting back `~1.1` for the time being.

**Comment by GrahamCampbell** [comment]
:-1: You are looking at the 1.2 branch.

**Comment by GrahamCampbell** [comment]
For 1.1, see https://github.com/tchwork/utf8/tree/1.1.

**Comment by vlakoff** [comment]
There's no 1.2 stable, so it requires `~1.2@dev`, or `"minimum-stability": "dev"` composer.json option.

**Comment by vlakoff** [comment]
Found out my mistake, thanks. I wish the branch were named "develop" ;)

**Comment by GrahamCampbell** [comment]
We could just change the default branch to 1.1.
