### ISSUE TITLE
Patchwork\Utf8::ucwords() is not functionally equivalent to PHP's ucwords()

### ISSUE THREAD

**Issue by martinkiva** [tchwork/utf8#38]
PHP's ucwords implementation converts the first character to upper case.
This libraries ucwords converts the first character to upper case AND the rest of the characters to lowercase.

e.g.
$str = "MARY had A Little lamb aND sHe lOVED IT So";
echo ucwords($str); // MARY Had A Little Lamb AND SHe LOVED IT So
echo Patchwork\Utf8::ucwords($str); // Prints Mary Had A Little Lamb And She Loved It So

**Comment by nicolas-grekas** [comment]
Closed via 4932c8d350b7b04fee6bf06201a6c7bdd909b328
Thanks you @martinkiva
