### ISSUE TITLE
mb_convert_encoding() Definition Needs to Check for Existing Definitions

### ISSUE THREAD

**Issue by pihish** [tchwork/utf8#54]
mb_convert_encoding() method is currently being defined in the global scope.  If a definition of it has already been defined by another library, it needs to not try to redefine it.  

Original conflict found between Patchwork and [symphony/polyfill-mbstring](https://github.com/symfony/polyfill-mbstring) when running composer update.

**Comment by nicolas-grekas** [comment]
Will be fixed in v1.3.0 see #55
Meanwhile, please ensure that you allow v1.3 in your composer.json file to get this next version.

**Comment by nicolas-grekas** [comment]
Fixed in v1.1.31, v1.2.6 and v1.3.0
