### ISSUE TITLE
Add "ext-intl": "*" to requirements.

### ISSUE THREAD

**Issue by fritzmg** [tchwork/utf8#58]
Since this package uses [Grapheme](http://php.net/manual/en/ref.intl.grapheme.php) functions and these functions are part of the PHP Intl extension, you should add
```
"ext-intl": "*"
```
to the requirements in your `composer.json`. Note that, while PHP Intl is alredy integrated into PHP since PHP `5.3.0`, some distributions still use a PHP binary _without_ PHP Intl, thus it is possible to run into errors like these:
```
Fatal error: Call to undefined function Patchwork\grapheme_strlen() in …/vendor/patchwork/utf8\src/Patchwork/Utf8.php on line 234
```
if you try to use `Patchwork::Utf8` without having the PHP Intl extension enabled (or without having a PHP binary that already integrates the intl extension).

**Comment by nicolas-grekas** [comment]
This package provides the missing functions implemented in plain PHP when intl is missing. That's we it doesn't have to require ext-intl. To load the missing functions, you have to bootstrap them, as documented in the readme:
https://github.com/tchwork/utf8#usage

**Comment by fritzmg** [comment]
I see, thx for the clarification :)
