### ISSUE TITLE
UndefinedFunctionException: Attempted to call function "iconv" from namespace "Symfony\Polyfill\Mbstring".

### ISSUE THREAD

**Issue by iman2420** [tchwork/utf8#71]
i try to run console server by this line:

    php app/console server:run xxx.xxx.xxx.xxx:8000 --docroot=public_html

but i give this error:

    

    `Fatal error: Uncaught 
    Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "iconv" from namespace "Symfony\Polyfill\Mbstring". in /home/raghibkosh/public_html/enews/vendor/symfony/polyfill-    mbstring/Mbstring.php:520
    Stack trace:
    #0 /home/raghibkosh/public_html/enews/vendor/symfony/polyfill- 
    mbstring/bootstrap.php(46): Symfony\Polyfill\Mbstring\Mbstring::mb_strwidth('  
    [Symfony\\Comp...', 'ASCII')
    #1  /home/raghibkosh/public_html/enews/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1106): mb_strwidth('  [Symfony\\Comp...', 'ASCII')
    #2  /home/raghibkosh/public_html/enews/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(650): Symfony\Component\Console\Application->stringWidth('  [Symfony\\Comp...')
    #3 /home/raghibkosh/public_html/enews/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php(105): Symfony\Component\Console\Application->renderException(Object(Symfony\Component\Debug\Exception\UndefinedFunctionExcep in /home/raghibkosh/public_html/enews/vendor/symfony/polyfill-mbstring/Mbstring.php on line 520`

> PHP 7.0.32 (cli) (built: Oct  5 2018 15:45:03) ( NTS )

> Composer version 1.7.2 2018-08-16 16:57:12

> CentOS Linux release 7.5.1804 (Core)

How to resolve this problem?

**Comment by nicolas-grekas** [comment]
Maybe because neither the iconv extension nor the iconv polyfill are installed.
But this is the wrong repo.
