### ISSUE TITLE
Default normalization is NFD, not NFC as stated (on PHP 7.4)

### ISSUE THREAD

**Issue by bafetk** [tchwork/utf8#75]
Using PHP 7.4, Patchwork/utf8 claims NFC as the default normalization. However, it is hardcoded to use "4" as the normalization. This is actually NFD.

Here are the constant values in PHP 7.4:
	Normalizer::FORM_C => 16
	Normalizer::FORM_D => 4
	Normalizer::FORM_KC => 32
	Normalizer::FORM_KD => 8
	Normalizer::NONE => 2

**Comment by nicolas-grekas** [comment]
Good catch, would you mind sending a PR to fix this?

**Comment by nicolas-grekas** [comment]
Actually, the default is still NFC, because we don't use the value of native constants.
I'm still singing values with latest PHP versions.
Thanks for the report.
